name: Deploy to Fly.io

on:
  push:
    branches:
      - main # ou a branch que você usa para produção

jobs:
  deploy:
    name: Deploy no Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: ?? Checkout do código
        uses: actions/checkout@v3

      - name: ?? Instalar o Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: ?? Fazer deploy para Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
